### ISSUE TITLE
Move repository to pokemongo-proto organization

### ISSUE THREAD

**Issue by BrunnerLivio** [BrunnerLivio/pokemongo-game-master#47]
Today @AeonLucid declared his [POGOProtos ](https://github.com/AeonLucid/POGOProtos)repository as "no longer maintained". This is unfortunate for depending developers. Since a shift of main contributor is always a tricky situation, I suggest we move the repository "pokemongo-game-master" and "pokemgo-json-pokedex" repo in an organization, so if I do not want to maintain those repository in the future, it would not change the repository address. 

I would also highly welcome @Furtif to join this repository with this [POGOProtos ](https://github.com/Furtif/POGOProtos) repository.

We can move the repository if the main contributors agree with this. @celandro @dandesousa

I have created an organization in advance: https://github.com/pokemongo-proto

**Comment by Furtif** [comment]
I think that it should not give a proper name, this is a function only if you want to add others such as game master etc ... or give a name easy and direct people who read say it is not, the rest thing that is give an "almost" good name that re-lists most or a large percentage in the feat will be more effective .. just give an idea then do as you like ..

**Comment by celandro** [comment]
I think a group name and sub projects is appropriate.

I would contribute pogoprotos-java and the game master repo. Preferably I
would like pogoprotos-java released with every update automatically.

**Comment by Furtif** [comment]
ok nothing I have to say, this does not belong to me, neither belongs to any of any developer even if I use or stop using .. it's just a matter of conscience, said different, good use or do, doing is not real because nothing is done who does it really is who created it, hence the problems with bots etc normal nothing to say, if those who made a legal api believe that would make more money than with the shop in the app since all or 99% of them use or used bots or scan among others ... I spoke in the "name" right, I am not criticizing the choice or another just say that a "base", well let's say "base" is the name:
base-protos
base-game-master
base-xxxxx
base-yyy
As I said before, that's just the idea.

sorry for bad english

**Comment by BrunnerLivio** [comment]
> should not give a proper name, this is a function only if you want to add others such as game master etc 

Good point. I changed it to pokemongo-dev-contrib (pokemogo-dev is already taken). Is that good?

> Preferably I would like pogoprotos-java released with every update automatically.

How you would want to achieve that?

@Furtif sorry I do not understand what you mean :/

**Comment by dandesousa** [comment]
I agree with @celandro and @BrunnerLivio on the approach and I'm not picky on names, I think the pokemongo-dev-contrib is reasonable. I'm in the midst of a largish project at the moment directly related to pogo and I will see what I'm doing that I can potentially contribute back to the org in terms of other projects that people might find useful.

**Comment by BrunnerLivio** [comment]
I've moved the repositories

https://github.com/pokemongo-dev-contrib/pokemongo-game-master
https://github.com/pokemongo-dev-contrib/pokemongo-json-pokedex

Feel free to move any other repository (but discuss it first on discord or email with us)
